apiVersion: v1
kind: Service
metadata:
  name: {{ include "yaci-store.fullname" . }}
  labels:
    {{- include "yaci-store.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "yaci-store.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
