postgres-operator:
  enabled: true
  fullnameOverride: "postgres-operator"

  configKubernetes:
    pod_environment_configmap: "pg-system/pod-environment"
    pod_environment_secret: "minio-credentials"
    enable_pod_antiaffinity: false

  configAwsOrGcp:
    aws_region: "minio"               # Your custom region (use appropriate value for your setup)
    wal_s3_bucket: "pg-wal"           # Bucket for WAL archive
  
  configLogicalBackup:
    logical_backup_s3_bucket: "pg-backups"
    logical_backup_s3_endpoint: "http://minio:9000"
    logical_backup_s3_region: "minio"
    logical_backup_docker_image: "registry.opensource.zalan.do/acid/logical-backup:latest"
    logical_backup_schedule: "0 1 * * *"  # Daily full logical backups at 01:00
    logical_backup_s3_retention_time: "7d"  # Keep backups for 7 days
    # If you want to add more, use official keys: https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values.yaml
  
  configPostgresPodResources:
    default_cpu_limit: "1"
    default_cpu_request: 100m
    default_memory_limit: 500Mi
    default_memory_request: 100Mi
    min_cpu_limit: 250m
    min_memory_limit: 250Mi
  
  configLoadBalancer:
    db_hosted_zone: svc.cluster.local
    enable_master_load_balancer: true
    enable_master_pooler_load_balancer: true
    enable_replica_load_balancer: true
    enable_replica_pooler_load_balancer: true
    external_traffic_policy: "Cluster"
    master_dns_name_format: "{cluster}.{namespace}.{hostedzone}"
    replica_dns_name_format: "{cluster}-repl.{namespace}.{hostedzone}"

postgres-operator-ui:
  enabled: true
  fullnameOverride: "postgres-operator-ui"
  envs:
    targetNamespace: "zpg-system"
  extraEnvs:
    - name: SPILO_S3_BACKUP_PREFIX
      value: spilo/
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: rootUser
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: rootPassword
    - name: AWS_DEFAULT_REGION
      value: minio
    - name: AWS_ENDPOINT
      value: http://minio:9000
    - name: WALE_S3_ENDPOINT
      value: http+path://minio:9000
    - name: WALE_S3_BUCKET
      value: pg-wal
    - name: SPILO_S3_BACKUP_BUCKET
      value: pg-wal
  
minio:
  enabled: true
  fullnameOverride: "minio"
  replicas: 1
  # Minio requires 2 to 16 drives for erasure code (drivesPerNode * replicas)
  # https://docs.min.io/docs/minio-erasure-code-quickstart-guide
  # Since we only have 1 replica, that means 2 drives must be used.
  drivesPerNode: 2
  ## Use existing Secret that store following variables:
  ##
  ## | Chart var             | .data.<key> in Secret    |
  ## |:----------------------|:-------------------------|
  ## | rootUser              | rootUser                 |
  ## | rootPassword          | rootPassword             |
  ##
  ## All mentioned variables will be ignored in values file.
  ## .data.rootUser and .data.rootPassword are mandatory,
  ## others depend on enabled status of corresponding sections.
  existingSecret: minio-credentials
  buckets:
    - name: pg-wal
    - name: pg-wal-logs
    - name: pg-backups
  service:
    port: 9000
  persistence:
    enabled: true
    size: 10Gi

