{{- with .Values.cardanoBacker }}
{{- if .enabled }}
{{- range $count := until (int .backerCount) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cardano-backer-{{ $count }}
  name: cardano-backer-{{ $count }}
spec:
  ports:
    - name: {{ add .initialHTTPPort $count | default "5666" | quote }}
      port: {{ add .initialHTTPPort $count | default 5666 }}
      targetPort: {{ add .initialHTTPPort $count | default 5666 }}
      protocol: TCP
  selector:
    app: cardano-backer-{{ $count }}
---
{{- end }}
{{- end }}
{{- end }}
