{{- $root := .Values -}}
{{ with .Values.cardanoBacker }}
{{- $backer := . -}}
{{- if $backer.enabled -}}
{{- range $count := until (int .backerCount) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cardano-backer-{{ $count }}
  name: cardano-backer-{{ $count }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardano-backer-{{ $count }}
  template:
    metadata:
      labels:
        app: cardano-backer-{{ $count }}
    spec:
      restartPolicy: Always
      {{- if $backer.tolerations }}
      tolerations:
        {{ with index $backer.tolerations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if $backer.affinity }}
      affinity:
        {{ with index $backer.affinity }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: cardano-backer-{{ $count }}
          image: "{{ $backer.image.repository }}:{{ $backer.image.tag }}"
          # Update the command and args if you need to pass the counter/port
          env:
            - name: BACKER_COUNTER
              value: {{ $count | quote }}
            - name: HTTP_PORT
              value: {{ add $backer.initialHTTPPort $count | default 5666 | quote }}
            - name: KERIA_CURLS_PROTO
              value: {{ $backer.keriaCurlsProto | default "https" | quote }}
            - name: KERIA_CURLS_EXTERNAL_HOST_TLD
              value: {{ $root.ingressTLDs | first | quote }}
            - name: KERIA_CURLS_URL
              value: "$(KERIA_CURLS_PROTO)://backer-{{ $count }}.$(KERIA_CURLS_EXTERNAL_HOST_TLD)"
            - name: NETWORK
              value: {{ $backer.network | default "preprod" | quote }}
            - name: OGMIOS_HOST
              value: {{ $backer.ogmiosHost | default "ogmios" | quote }}
            - name: OGMIOS_PORT
              value: {{ $backer.ogmiosPort | default "1337" | quote }}
            - name: BACKER_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ $backer.secret.name }}
                  key: {{ $backer.secret.saltKey }}
            - name: WALLET_ADDRESS_CBORHEX
              valueFrom:
                secretKeyRef:
                  name: {{ $backer.secret.name }}
                  key: {{ $backer.secret.walletKey }}
          command: ["bash", "/configmap/entrypoint.sh"]
          ports:
            - containerPort: {{ add $backer.initialHTTPPort $count | default 5666 }}
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/var/keri
              name: cardano-backer-data
            - mountPath: /configmap
              name: cardano-backer-configmap
      volumes:
        - name: cardano-backer-data
          persistentVolumeClaim:
            claimName: cardano-backer-data
        - name: cardano-backer-configmap
          configMap:
            name: cardano-backer-configmap
  volumeClaimTemplates:
    - metadata:
        name: cardano-backer-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $backer.volumeSize | default "1Gi" }}
{{- end }}
{{ end }}
{{ end }}
