{{- $root := .Values -}}
{{ with .Values.cardanoBacker }}
{{- $backer := . -}}
{{- if $backer.ingress.enabled -}}
{{- range $count := until (int .backerCount) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardano-backer-{{ $count }}
  labels:
    app: cardano-backer
  labels:
  {{- with $backer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $TLD := $root.ingressTLDs }}
      {{- range $host := $backer.ingress.hosts }}
    - host: {{ $host }}-{{ $count }}.{{ $TLD }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cardano-backer-{{ $count }}
                port:
                  number: {{ add $backer.initialHTTPPort $count }}
      {{- end }}
    {{- end }}
  tls:
    - hosts:
    {{- range $TLD := $root.ingressTLDs }}
      {{- range $host := $backer.ingress.hosts }}
        - "{{ $host }}-{{ $count }}.{{ $TLD }}"
      {{- end }}
    {{- end }}
---
{{- end }}
{{ end }}
{{ end }}
