{{- $root := .Values -}}
{{ with .Values.cardanoBacker }}
{{- if .ingress.enabled -}}
{{- range $count := until (int .backerCount) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardano-backer-{{ $count }}-ingress
  labels:
    app: cardano-backer-{{ $count }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $TLD := $root.ingressTLDs }}
      {{- range $host := .ingress.hosts }}
    - host: {{ $host }}-{{ $count }}.{{ $TLD }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cardano-backer-{{ $count }}
                port:
                  number: {{ add .initialHTTPPort $count | default 5666 }}
      {{- end }}
    {{- end }}
  tls:
    - hosts:
    {{- range $TLD := $root.ingressTLDs }}
      {{- range $host := .ingress.hosts }}
        - "{{ $host }}-{{ $count }}.{{ $TLD }}"
      {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
