{{ with .Values.credIssuanceUI }}
{{ if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cip45
  name: cip45
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cip45
  template:
    metadata:
      labels:
        app: cip45
    spec:
      {{- if .tolerations }}
      tolerations:
        {{ with index .tolerations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{ with index .affinity }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: cip45
          image: "{{ .image.repository }}:{{ .image.tag }}"
          ports:
            - containerPort: {{ .port | default 80 }}
              protocol: TCP
{{ end }}
{{ end }}
