apiVersion: v1
kind: Service
metadata:
  labels:
    app: cred-issuance
  name: cred-issuance
spec:
  ports:
    - name: {{ .port | default "3001" | quote }}
      port: {{ .port | default "3001" }}
      targetPort: {{ .port | default "3001" }}
  selector:
    app: cred-issuance
