{{ with .Values.credIssuanceUI }}
{{ if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cred-issuance-ui
  name: cred-issuance-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cred-issuance-ui
  template:
    metadata:
      labels:
        app: cred-issuance-ui
    spec:
      {{- if .tolerations }}
      tolerations:
        {{ with index .tolerations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{ with index .affinity }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: cred-issuance-ui
          image: "{{ .image.repository }}:{{ .image.tag }}"
          env:
            - name: VITE_SERVER_URL
              value: {{ .serverUrl | default "http://cred-issuance:3001" }}
          ports:
            - containerPort: {{ .port | default 80 }}
              protocol: TCP
{{ end }}
{{ end }}
