{{ with .Values.veridianDocusign }}
{{ if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: veridian-docusign
  name: veridian-docusign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veridian-docusign
  template:
    metadata:
      labels:
        app: veridian-docusign
    spec:
      {{- if .tolerations }}
      tolerations:
        {{ with index .tolerations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{ with index .affinity }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: veridian-docusign
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .port | default 80 }}
              protocol: TCP
{{ end }}
{{ end }}
