{{ with .Values.keria }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keria
  name: keria
spec:
  ports:
    {{- range $port := .ports }}
    - name: {{ $port | quote }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
  selector:
    app: keria
{{ end }}
