{{ with .Values.keria }}
{{ if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keria-configmap
data:
  initContainer-entrypoint.sh: |
    #!/bin/sh
    set -e

    export KERIA_RENDERED_CURLS=$(for keria_curl in ${KERIA_CURLS}; do echo $keria_curl; done | jq -cRn '[inputs]')
    envsubst < /configmap/witness.json.tpl > /config/witness.json

    if [ "$KERIA_IURLS" == "autodetect" ]
    then
      CHART_NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
      WITNESS_COUNT=$(kubectl get statefulset -n $CHART_NAMESPACE | grep -E '^witness-[0-9]+$' | wc -l)
      KERIA_IURLS=""
      for wit in $(seq 0 $((WITNESS_COUNT-1)))
      do
        WITNESS_OOBI=$(kubectl logs -n ${CHART_NAMESPACE} witness-$seq-0 2>/dev/null | grep ^Witness | awk '{print $NF}')
        WITNESS_URL=https://witness-${seq}.${INGRESS_TLD}/oobi/${WITNESS_OOBI}/controller?role=witness
        KERIA_IURLS="$KERIA_IURLS $WITNESS_URL"
      done
      envsubst < /configmap/backer-oobis.json.tpl > /config/backer-oobis.json
    else
      export KERIA_RENDERED_IURLS=$(for keria_iurl in ${KERIA_IURLS}; do echo $keria_iurl; done | jq -cRn '[inputs]')
      envsubst < /configmap/backer-oobis.json.tpl > /config/backer-oobis.json
    fi

  witness.json.tpl: |
    {
      "witness": {
        "dt": "2022-01-20T12:57:59.823350+00:00",
        "curls": ${KERIA_RENDERED_CURLS}
      },
      "dt": "2022-01-20T12:57:59.823350+00:00",
      "iurls": [
      ]
    }

  backer-oobis.json.tpl: |
    {
      "dt": "2022-01-20T12:57:59.823350+00:00",
      "keria": {
        "dt": "2022-01-20T12:57:59.823350+00:00",
        "curls": ${KERIA_RENDERED_CURLS}
      },
      "iurls": ${KERIA_RENDERED_IURLS}
    }

{{ end }}
{{ end }}
