{{ with .Values.keriaProvisioning }}
{{ if .enabled }}
{{ if eq .kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keria-provisioning
  name: keria-provisioning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keria-provisioning
  template:
    metadata:
      labels:
        app: keria-provisioning
    spec:
      restartPolicy: Always
      {{- if .tolerations }}
      tolerations:
        {{ with index .tolerations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{ with index .affinity }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: keria-provisioning
          image: "{{ .image.repository }}:{{ .image.tag }}"
          env:
            - name: EXTERNAL_PROVISIONING_SERVICE_URL
              value: {{ .externalProvisioningServiceUrl | default "http://keria-provisioning.example.com" }}
            - name: INTERNAL_KERIA_URL
              value: {{ .internalKeriaUrl | default "http://keria:3903" }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .db.secret.name }}
                  key: {{ .db.secret.hostKey }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .db.secret.name }}
                  key: {{ .db.secret.usernameKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .db.secret.name }}
                  key: {{ .db.secret.passwordKey }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .db.secret.name }}
                  key: {{ .db.secret.dbNameKey }}
            - name: DB_PORT
              value: {{ .dbPort | default "5432" | quote }}
            - name: DB_SCHEMA
              value: {{ .dbSchema | default "keria" }}
            - name: DB_URL
              value: {{ .dbUrl | default "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)" }}
            - name: H2_CONSOLE_ENABLED
              value: {{ .h2ConsoleEnabled | default "false" | quote }}
            - name: SES_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .smtp.secret.name }}
                  key: {{ .smtp.secret.sesAccessKeyIdKey }}
            - name: SES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .smtp.secret.name }}
                  key: {{ .smtp.secret.sesPasswordKey }}
            - name: AWS_REGION
              value: {{ .smtp.awsRegion | default "eu-west-1" | quote }}
            - name: SMTP_FROM
              value: {{ .smtp.from | default "admin@example.com" }}
          ports:
            - containerPort: {{ .port | default 9030 }}
              protocol: TCP

{{ end }}
{{ end }}
{{ end }}
