apiVersion: v1
kind: Service
metadata:
  labels:
    app: keria
  name: keria
spec:
  ports:
    - name: "3901"
      port: 3901
      targetPort: 3901
    - name: "3902"
      port: 3902
      targetPort: 3902
    - name: "3903"
      port: 3903
      targetPort: 3903
  selector:
    app: keria
