{{ with .Values.keria }}
{{ if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keria-configmap
data:
  initContainer-entrypoint.sh: |
    #!/bin/sh

    export KERIA_RENDERED_CURLS=$(for keria_curl in ${KERIA_CURLS}; do echo $keria_curl; done | jq -cRn '[inputs]')
    envsubst < /configmap/witness.json.tpl > /config/witness.json

    if [ "$KERIA_IURLS" == "autodetect" ]
    then
      KERIA_IURLS=""
      CHART_NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
      for seq in $(seq 0 $((WITNESS_COUNT-1)))
      do
        WITNESS_OOBI=""
        WITNESS_PORT=$(( INITIAL_WITNESS_PORT + seq ))
        WITNESS_BASE_URL=http://witness-${seq}:${WITNESS_PORT}
        while [[ -z "$WITNESS_OOBI" ]]; do
          WITNESS_OOBI=$(curl -s $WITNESS_BASE_URL/oobi | jq -r .k.[] 2> /dev/null)
          sleep 1
        done
        WITNESS_PUBLIC_URL=${KERIA_IURLS_PROTOCOL:-https}://witness-${seq}.${INGRESS_TLD}/oobi/${WITNESS_OOBI}/controller?role=witness
        KERIA_IURLS="$KERIA_IURLS $WITNESS_PUBLIC_URL"
      done
    fi
    export KERIA_RENDERED_IURLS=$(for keria_iurl in ${KERIA_IURLS}; do echo $keria_iurl; done | jq -cRn '[inputs]')
    envsubst < /configmap/backer-oobis.json.tpl > /config/backer-oobis.json

  witness.json.tpl: |
    {
      "witness": {
        "dt": "2022-01-20T12:57:59.823350+00:00",
        "curls": ${KERIA_RENDERED_CURLS}
      },
      "dt": "2022-01-20T12:57:59.823350+00:00",
      "iurls": [
      ]
    }

  backer-oobis.json.tpl: |
    {
      "tocks": {
        "escrower": 1.0
      },
      "dt": "2022-01-20T12:57:59.823350+00:00",
      "keria": {
        "dt": "2022-01-20T12:57:59.823350+00:00",
        "curls": ${KERIA_RENDERED_CURLS}
      },
      "iurls": ${KERIA_RENDERED_IURLS}
    }

{{ end }}
{{ end }}
