apiVersion: batch/v1
kind: Job
metadata:
  name: cf-idw-secrets-create
spec:
  ttlSecondsAfterFinished: 180
  template:
    metadata:
      name: cf-idw-secrets-create
    spec:
      serviceAccountName: cf-idw-secrets-create-job-sa
      restartPolicy: Never
      volumes:
        - name: shared-data
          emptyDir: {}  # Shared volume between containers
        - name: script-volume
          configMap:
            name: job-script
            defaultMode: 0755
      initContainers:
        - name: init-container
          image: cardanofoundation/cf-keria-passcode-gen:7e77930e
          command: ["bash", "-c", "node passcode-gen.js > /shared/passcode"]
          # conditionally add environment if a .Values.keria.passCode was provided
          {{- if .Values.keria.passCode }}
          env:
            - name: KERIA_PASSCODE
              value: {{ .Values.keria.passCode }}
          {{- end }}
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      containers:
        - name: job-container
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "/scripts/create-secret.sh"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
              readOnly: true
            - name: shared-data
              mountPath: /shared  # Mounting the shared volume
