apiVersion: v1
kind: ConfigMap
metadata:
  name: job-script
data:
  create-secret.sh: |
    #!/bin/sh
    if [ -z "${KERIA_PASSCODE}" ]
    then
      PASSCODE=$(cat /shared/passcode)
    else
      PASSCODE="${KERIA_PASSCODE}"
    fi
    kubectl create secret generic cf-idw-secrets --from-literal=KERIA_PASSCODE="$PASSCODE" -n $NAMESPACE
