{{- if .Values.keria.secret.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cf-idw-secrets-create-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-idw-secrets-create-role-binding
subjects:
  - kind: ServiceAccount
    name: cf-idw-secrets-create-job-sa
roleRef:
  kind: Role
  name: cf-idw-secrets-create-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-idw-secrets-create-job-sa
{{- end }}
