{{ with .Values.vlei }}
{{ if .enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vlei
  name: vlei
spec:
  ports:
    - name: {{ .port | default "7723" | quote }}
      port: {{ .port | default 7723 }}
      targetPort: {{ .port | default 7723 }}
  selector:
    app: vlei
{{ end }}
{{ end }}
