{{ with .Values.witness }}
{{ if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: witness
  name: witness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: witness
  template:
    metadata:
      labels:
        app: witness
    spec:
      {{- if .tolerations }}
      tolerations:
        {{ with index .tolerations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{ with index .affinity }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: witness
          image: "{{ .image.repository }}:{{ .image.tag }}"
          ports:
          {{- range $port := .ports }}
            - containerPort: {{ $port }}
              hostPort: {{ $port }}
              protocol: TCP
          {{- end }}
{{ end }}
{{ end }}
