{{- $root := .Values -}}
{{ with .Values.witness }}
{{- $witness := . -}}
{{- range $pool := .witPool }}
{{- if $pool.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: witness-{{ $pool.name }}
  name: witness-{{ $pool.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: witness-{{ $pool.name }}
  template:
    metadata:
      labels:
        app: witness-{{ $pool.name }}
    spec:
      restartPolicy: Always
      {{- if .tolerations }}
      tolerations:
        {{ with index .tolerations }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{ with index .affinity }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: witness
          image: "{{ $pool.image.repository }}:{{ $pool.image.tag }}"
          command: ["kli", "witness", "start"]
          ports:
          {{- range $port := $pool.ports }}
            - containerPort: {{ $port }}
              hostPort: {{ $port }}
              protocol: TCP
          {{- end }}
          volumeMounts:
            - mountPath: /usr/local/var/keri
              name: keri-data
      volumes:
        - name: keri-data
          persistentVolumeClaim:
            claimName: keri-data

  volumeClaimTemplates:
    - metadata:
        name: keri-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $pool.volumeSize | default "1Gi" }}

{{ end }}
{{ end }}
{{ end }}
