{{ with .Values.witness }}
{{ if .enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: witness
  name: witness
spec:
  ports:
    {{- range $port := .ports }}
    - name: {{ $port | quote }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
  selector:
    app: witness
{{ end }}
{{ end }}
