{{- $root := .Values -}}
{{ with .Values.witness }}
{{- $witness := . -}}
{{- if $witness.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: witness
  name: witness
spec:
  ports:
    {{- range $port := $witness.ports }}
    - name: {{ $port | quote }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
  selector:
    app: witness
{{ end }}
{{ end }}
