{{- $root := .Values -}}
{{ with .Values.witness }}
{{- $witness := . -}}
{{- range $pool := .witPool }}
{{- if $pool.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: witness-{{ $pool.name }}
  name: witness-{{ $pool.name }}
spec:
  ports:
    {{- range $port := $pool.ports }}
    - name: {{ $port | quote }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
  selector:
    app: witness-{{ $pool.name }}
{{ end }}
{{ end }}
{{ end }}
