kind: ConfigMap
apiVersion: v1
metadata:
  name: witness
data:
  witness-init.sh: |
    #!/bin/bash
    if [ ! -e ${KERI_VAR_DIR}/db/witness/data.mdb ]; then
      mkdir -p ${KERI_VAR_DIR}/data
      mkdir -p ${KERI_SCRIPT_DIR}/keri/cf
      set -e
      export KERIA_CURLS="${KERIA_CURLS_URL}"
      export KERIA_RENDERED_CURLS=$(for keria_curl in ${KERIA_CURLS}; do echo $keria_curl; done | jq -cRn '[inputs]')
      export WITNESS_NAME="wit${WITNESS_COUNTER}"
      envsubst < /configmap/witness.json.tpl > ${KERI_SCRIPT_DIR}/keri/cf/${WITNESS_NAME}.json
      cat ${KERI_SCRIPT_DIR}/keri/cf/${WITNESS_NAME}.json
      kli init --name ${WITNESS_NAME} --nopasscode --config-dir ${KERI_SCRIPT_DIR} --config-file ${WITNESS_NAME}.json
      kli incept --name ${WITNESS_NAME} --alias ${WITNESS_NAME} --config ${KERI_SCRIPT_DIR} --file keri/cf/${WITNESS_NAME}.json
    fi

  witness.json.tpl: |
    {
      "${WITNESS_NAME}": {
        "dt": "2022-01-20T12:57:59.823350+00:00",
        "curls": ${KERIA_RENDERED_CURLS}
      },
      "dt": "2022-01-20T12:57:59.823350+00:00",
      "iurls": [
      ]
    }

  wil-witness-sample.json: |
    {
      "transferable": false,
      "wits": [],
      "icount": 1,
      "ncount": 1,
      "isith": "1",
      "nsith": "1"
    }
