kind: ConfigMap
apiVersion: v1
metadata:
  name: witness
data:
  witness-init.sh: |
    #!/bin/bash
    if [ ! -e ${KERI_SCRIPT_DIR}/data/wil-witness-sample.json ]; then
      mkdir -p ${KERI_SCRIPT_DIR}/data
      kli init --name witness --nopasscode --config-dir ${KERI_SCRIPT_DIR} --config-file witness
      kli incept --name witness --alias witness --config ${KERI_SCRIPT_DIR} --file ${KERI_DEMO_SCRIPT_DIR}/data/wil-witness-sample.json
    fi
