{{- $root := .Values -}}
{{ with .Values.witness }}
{{- $witness := . -}}
{{- if $witness.enabled -}}
{{- range $count := until (int .witnessCount) }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: witness
  name: witness-{{ $count }}
spec:
  ports:
    - name: {{ add $witness.initialHTTPPort $count | quote }}
      port: {{ add $witness.initialHTTPPort $count }}
      protocol: TCP
      targetPort: {{ add $witness.initialHTTPPort $count }}
  selector:
    app: witness-{{ $count }}
{{- end }}
{{ end }}
{{ end }}
