{{ with .Values.witness }}
{{ if .enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: witness
  name: witness
spec:
  ports:
    {{- range $port := .ports }}
    - containerPort: {{ $port }}
      hostPort: {{ $port }}
      protocol: TCP
    {{- end }}
  selector:
    app: witness
{{ end }}
{{ end }}
