apiVersion: v1
kind: Service
metadata:
  name: {{ include "cf-ogmios.fullname" . }}
  labels:
    {{- include "cf-ogmios.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cf-ogmios.selectorLabels" . | nindent 4 }}
  ports:
    - name: ogmios
      port: {{ .Values.port }}
      targetPort: ogmios
      protocol: TCP
