{{ if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: uverify-backend
spec:
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  selector:
    app: uverify-backend
{{ end }}
