apiVersion: v1
kind: Service
metadata:
  name: {{ include "cf-kupo.fullname" . }}
  labels:
    {{- include "cf-kupo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cf-kupo.selectorLabels" . | nindent 4 }}
  ports:
    - name: kupo
      port: {{ .Values.port }}
      targetPort: kupo
      protocol: TCP