swapClient:
  enabled: true
  image:
    repository: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cardano-ibc-swap-client
    tag: ""
    pullPolicy: IfNotPresent
  port: 3000
  gatewayEndpoint: http://gateway:8000
  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "500m"
      memory: 1Gi

explorer:
  enabled: true
  image:
    repository: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cardano-ibc-explorer
    tag: ""
    pullPolicy: IfNotPresent
  port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "500m"
      memory: 1Gi

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []