apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  rootUser: {{ .Values.minio.rootUser | default "pg-operator" | b64enc }}
  rootPassword: {{ default (randAlphaNum 16) | b64enc }}
