apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-environment
data:
  {{ range $key, $val := index .Values "postgres-operator" "zpg" "podEnvironment" }}
  {{ if (include "isMap" $val) -}}
  {{ $key }}: '{{ $val }}'
  CLONE_{{ $key }}: '{{ $val }}'
  STANDBY_{{ $key }}: '{{ $val }}'
  {{ else }}
  {{ $key }}: "{{ $val }}"
  CLONE_{{ $key }}: "{{ $val }}"
  STANDBY_{{ $key }}: "{{ $val }}"
  {{ end }}
  {{ end }}
