ingressTLDs:
  - "example.com"

credIssuance:
  enabled: true
  image:
    repository: "cardanofoundation/cf-cred-issuance"
    tag: "main"
  port: 3001
  ingress:
    enabled: true
    hosts:
      - cred-issuance

credIssuanceUI:
  enabled: true
  image:
    repository: "cardanofoundation/cf-cred-issuance-ui"
    tag: "main"
  port: 80
  ingress:
    enabled: true
    hosts:
      - cred-issuance-ui

cip45:
  enabled: true
  image:
    repository: "cardanofoundation/cf-cip45-sample-dapp"
    tag: "main"
  port: 80
  ingress:
    enabled: true
    hosts:
      - cip45

keria:
  enabled: true
  image:
    repository: "cardanofoundation/cf-idw-keria"
    tag: "main"
  logLevel: "INFO"
  ports:
    - 3901
    - 3902
    - 3903
  ingress:
    enabled: true
    hosts:
      - name: keria
        port: 3901
      - name: keria-ext
        port: 3902
      - name: keria-boot
        port: 3903
  secret:
    name: cf-idw-secrets
    keriaPasscodeKey: KERIA_PASSCODE

keriaProvisioning:
  enabled: false
  kind: StatefulSet
  image:
    repository: "cardanofoundation/cf-keria-provisioning"
    tag: "main"
  port: 9030
  ingress:
    enabled: true
    hosts:
      - keria-provisioning
  smtp:
    secret:
      name: cf-idw-secrets
      sesAccessKeyIdKey: SES_ACCESS_KEY_ID
      sesPasswordKey: SES_SMTP_PASSWORD
  db:
    secret:
      name: cf-idw-secrets
      usernameKey: POSTGRES_USER
      passwordKey: POSTGRES_PASSWORD
      hostKey: POSTGRES_HOST
      dbNameKey: POSTGRES_DB

witness:
  enabled: true
  image:
    repository: "cardanofoundation/cf-idw-witness"
    tag: "0.1.1-customize-keria-docker-image-863f2c2-9956455103"
  witnessCount: 6
  initialHTTPPort: 5642
  initialTCPPort: 5632
  logLevel: "INFO"
  ingress:
    enabled: true
    hosts:
      - witness
