ingressTLDs:
  - "example.com"

credIssuance:
  enabled: true
  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-cred-issuance"
    tag: "0.1.1-develop-612b15f-9895437336"
  port: 3001
  ingress:
    enabled: true
    hosts:
      - cred-issuance

credIssuanceUI:
  enabled: true
  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-cred-issuance-ui"
    tag: "0.1.1-develop-612b15f-9895437336"
  port: 80
  ingress:
    enabled: true
    hosts:
      - cred-issuance-ui

keria:
  enabled: true
  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-idw-keria"
    tag: "0.1.1-develop-612b15f-9895437336"
  ports:
    - 3901
    - 3902
    - 3903
  ingress:
    enabled: true
    hosts:
      - name: keria
        port: 3901
      - name: keria-ext
        port: 3902
      - name: keria-boot
        port: 3903
  secret:
    name: cf-idw-secrets
    keriaPasscodeKey: KERIA_PASSCODE

keriaProvisioning:
  enabled: true
  kind: StatefulSet
  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-keria-provisioning"
    tag: "1.0.0-SNAPSHOT-PR6-b8b2d2b-10079980400"
  port: 9030
  ingress:
    enabled: true
    hosts:
      - keria-provisioning
  smtp:
    secret:
      name: cf-idw-secrets
      sesAccessKeyIdKey: SES_ACCESS_KEY_ID
      sesPasswordKey: SES_SMTP_PASSWORD
  db:
    secret:
      name: cf-idw-secrets
      usernameKey: POSTGRES_USER
      passwordKey: POSTGRES_PASSWORD
      hostKey: POSTGRES_HOST
      dbNameKey: POSTGRES_DB

witness:
  enabled: true
  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-idw-witness"
    tag: "0.1.1-customize-keria-docker-image-863f2c2-9956455103"
  port: 5631
  ingress:
    enabled: true
    hosts:
      - witness
