kube-prometheus-stack:
  enabled: true
  fullnameOverride: "kube-prometheus-stack"
  global:
    rbac:
      create: true
  grafana:
    plugins:
      - grafana-singlestat-panel
    sidecar:
      alerts:
        enabled: true
      datasources:
        enabled: true
      notifiers:
        enabled: true

metrics-server:
  enabled: true
  fullnameOverride: "metrics-server"
