kube-prometheus-stack:
  enabled: true
  fullnameOverride: "kube-prometheus-stack"
  global:
    rbac:
      create: true
  grafana:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
            isDefault: false
            editable: false
    plugins:
      - grafana-singlestat-panel
    sidecar:
      alerts:
        enabled: true
      datasources:
        enabled: true
      notifiers:
        enabled: true

metrics-server:
  enabled: true
  fullnameOverride: "metrics-server"
  apiService:
    annotations:
      somekey: "this-avoids-argocd-wanting-to-always-apply-null-annotations"

promtail:
  enabled: false
  fullnameOverride: "promtail"
  pipelineStages:
  - match:
      selector: '{namespace!=""} |~ ".*kube-probe/.*" !~ ".*stdout F $"'

loki:
  enabled: false
  fullnameOverride: "loki"
  loki:
    persistence:
      enabled: false
    storage:
      bucketNames:
        chunks: loki
        ruler: loki-ruler
        admin: loki-admin
      use_thanos_objstore: true
      object_store:
        type: s3
        s3:
          endpoint: loki-minio:9000
          insecure: true
          access_key_id: loki
          secret_access_key: vanfUEWu8mEbDze
        storage_prefix: loki
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    limits_config:
      retention_period: 336h           # global retention of 2 weeks (14 days)
      max_query_lookback: 336h         # generally should be ≤ retention_period
      allow_structured_metadata: true
      volume_enabled: true
    compactor:
      working_directory: /var/loki/compactor
      retention_enabled: true
      compaction_interval: 10m
      retention_delete_delay: 2h       # delay before actual deletion
      retention_delete_worker_count: 100
      delete_request_store: s3
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    pattern_ingester:
        enabled: true
    ruler:
      enable_api: true

  minio:
    enabled: true
    fullnameOverride: "loki-minio"
    rootUser: loki
    rootPassword: vanfUEWu8mEbDze
    buckets:
      - name: loki
      - name: loki-ruler
      - name: loki-admin
    service:
      port: 9000
    persistence:
      enabled: true

  deploymentMode: SingleBinary

  singleBinary:
    replicas: 1

  # Zero out replica counts of other deployment modes
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0
