apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-env
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | quote }}
  GRPC_HOST: {{ .Values.env.GRPC_HOST | quote }}
  GRPC_PORT: {{ .Values.env.GRPC_PORT | quote }}

  CARDANO_CHAIN_ID: {{ .Values.env.CARDANO_CHAIN_ID | quote }}
  CARDANO_NETWORK_MAGIC: {{ .Values.env.CARDANO_NETWORK_MAGIC | quote }}
  CARDANO_LIGHT_CLIENT_MODE: {{ .Values.env.CARDANO_LIGHT_CLIENT_MODE | quote }}
  CARDANO_EPOCH_NONCE_GENESIS: {{ .Values.env.CARDANO_EPOCH_NONCE_GENESIS | quote }}
  CARDANO_STABILITY_THRESHOLD_DEPTH: {{ .Values.env.CARDANO_STABILITY_THRESHOLD_DEPTH | quote }}
  CARDANO_STABILITY_THRESHOLD_UNIQUE_POOLS: {{ .Values.env.CARDANO_STABILITY_THRESHOLD_UNIQUE_POOLS | quote }}
  CARDANO_STABILITY_THRESHOLD_UNIQUE_STAKE_BPS: {{ .Values.env.CARDANO_STABILITY_THRESHOLD_UNIQUE_STAKE_BPS | quote }}

  HANDLER_JSON_PATH: {{ .Values.env.HANDLER_JSON_PATH | quote }}

  KUPO_ENDPOINT: {{ include "gateway.kupoEndpoint" . | quote }}
  OGMIOS_ENDPOINT: {{ include "gateway.ogmiosEndpoint" . | quote }}
  YACI_STORE_ENDPOINT: {{ printf "http://%s-yaci-store:8080" .Release.Name | quote }}
  CARDANO_CHAIN_HOST: {{ include "gateway.cardanoNodeHost" . | quote }}
  CARDANO_CHAIN_PORT: {{ .Values.env.CARDANO_CHAIN_PORT | quote }}

  GATEWAY_DB_HOST: {{ include "gateway.gatewayDbHost" . | quote }}
  GATEWAY_DB_NAME: {{ include "gateway.gatewayDbName" . | quote }}
  GATEWAY_DB_SYNCHRONIZE: {{ .Values.env.GATEWAY_DB_SYNCHRONIZE | quote }}

  HISTORY_DB_HOST: {{ include "gateway.historyDbHost" . | quote }}
  HISTORY_DB_NAME: {{ .Values.env.HISTORY_DB_NAME | default "yaci_store" | quote }}
  HISTORY_DB_USERNAME: {{ .Values.env.HISTORY_DB_USERNAME | default "yaci" | quote }}
