apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-app
  ports:
    - name: rest
      port: {{ .Values.restPort }}
      targetPort: rest
      protocol: TCP
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: grpc
      protocol: TCP
