{{- if and .Values.dapps.swapClient.enabled .Values.dapps.swapClient.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "dapps.swapFullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: swap-client
    app.kubernetes.io/part-of: cardano-ibc
  {{- with .Values.dapps.swapClient.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.dapps.swapClient.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.dapps.swapClient.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.dapps.swapClient.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- $paths := .paths | default (list (dict "path" "/" "pathType" "Prefix")) }}
          {{- range $paths }}
          - path: {{ .path | default "/" | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "dapps.swapFullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
