{{- if .Values.explorer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dapps.explorerFullname" . }}
  labels:
    app.kubernetes.io/name: ibc-explorer
    app.kubernetes.io/part-of: cardano-ibc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ibc-explorer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibc-explorer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: explorer
          image: {{ printf "%s:%s" .Values.explorer.image.repository (.Values.explorer.image.tag | default "latest") | quote }}
          imagePullPolicy: {{ .Values.explorer.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.explorer.port | toString | quote }}
            - name: HOST
              value: "0.0.0.0"
            - name: REACT_APP_CARDANO_CHAIN_ID
              value: {{ include "dapps.explorerCardanoChainId" . | toString | quote }}
            {{- with .Values.explorer.apiDomain }}
            - name: REACT_APP_API_DOMAIN
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.explorer.localOsmosisRpcEndpoint }}
            - name: REACT_APP_LOCALOSMOIS_RPC_ENDPOINT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.explorer.localOsmosisRestEndpoint }}
            - name: REACT_APP_LOCALOSMOIS_REST_ENDPOINT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.explorer.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.explorer.port }}
              protocol: TCP
          resources: {{- toYaml .Values.explorer.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dapps.explorerFullname" . }}
  labels:
    app.kubernetes.io/name: ibc-explorer
    app.kubernetes.io/part-of: cardano-ibc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ibc-explorer
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.explorer.port }}
      targetPort: http
      protocol: TCP
{{- end }}
