apiVersion: v1
kind: Service
metadata:
  name: yaci-address-balance-monitor
  labels:
    app: yaci-address-balance-monitor
spec:
  selector:
    app: yaci-address-balance-monitor
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
