{{- if .Values.gateway.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "gateway.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-rest
  {{- with .Values.gateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.gateway.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.gateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- $paths := .paths | default (list (dict "path" "/" "pathType" "Prefix")) }}
          {{- range $paths }}
          - path: {{ .path | default "/" | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "gateway.fullname" $ }}
                port:
                  name: rest
          {{- end }}
    {{- end }}
{{- end }}
